# HTCondor submit description file
# Everything with a leading # is a comment

universe                = docker
docker_image            = docker.lsv.uni-saarland.de/rkchikkala/htcondor-test:latest
initialdir              = /nethome/rkchikkala/soft_ware_project/test_repo/htcondor-test
executable              = /nethome/rkchikkala/soft_ware_project/test_repo/htcondor-test/scripts/run.sh
output                  = /data/users/rkchikkala/logs/soft_ware_project/test_repo/logfiles/run.sh.$(ClusterId).$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).out
error                   = /data/users/rkchikkala/logs/soft_ware_project/test_repo/logfiles/run.sh.$(ClusterId).$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).err
log                     = /data/users/rkchikkala/logs/soft_ware_project/test_repo/logfiles/run.sh.$(ClusterId).$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).log
request_CPUs            = 1
request_memory          = 10G
request_GPUs            = 1
requirements            = (GPUs_GlobalMemoryMb >= 16000) && (machine == "cl17lx.lsv.uni-saarland.de")
queue 1
